*&---------------------------------------------------------------------*
*& Report  ZTEST_JOAO2
*&
*&---------------------------------------------------------------------*

REPORT  ZTEST_JOAO2.

*TYPES: BEGIN OF ty_matdata,
"FETCH THE DATA FROM THE DATABASE TABLE
TYPES: BEGIN OF TY_EKKO,
       COMPANY_CODE TYPE BUKRS, "COMPANY CODE
       CURRENCY TYPE WAERS, "CURRENCY
       AMOUNT TYPE RLWRT, "PO AMOUNT1
END OF TY_EKKO.

"NOW WE ARE DEFINING AN INTERNAL TABLE
DATA:IT_EKKO TYPE TABLE OF TY_EKKO.

"THEN DEFINE STRUCTURE TYPE
DATA: ST_EKKO TYPE TY_EKKO,
        P_CODE TYPE BUKRS,
        P_DATE TYPE AEDAT,
        TEMP_CCODE TYPE BUKRS,
        TEMP_CURR TYPE WAERS.


"DEFINE VARIABLE TO OLD THE TOTAL PO AMOUNT
DATA V_TOTAL TYPE P DECIMALS 2.
"NOW, ON THE OUTPUT, INPUTE THE DATE RANGE TO GET THE NET AMOUNT OF ALL PO'S
"ARAMETERS: P_DFROM TYPE AEDAT, P_DTO TYPE AEDAT.

SELECT-OPTIONS: cODE FOR P_CODE.
SELECT-OPTIONS: DATE FOR P_DATE.

"SELECT-OPTION TO ASELECT A NUMBER OF COMPANY CODES AT THE SAME TIME
START-OF-SELECTION.
  SELECT BUKRS "
         WAERS " SELECT THREE FIELFS FROM THE DATABASE TABLE, COMPANY CODE, CURRENCY AND PO AMOUNT
         RLWRT " BASED ON THE CRITERIA ENTERED BY THE USER
    FROM EKKO INTO TABLE IT_EKKO WHERE AEDAT IN DATE AND BUKRS IN CODE. 
  SORT IT_EKKO BY COMPANY_CODE CURRENCY ASCENDING.

END-OF-SELECTION.
  LOOP AT IT_EKKO INTO ST_EKKO.
    V_TOTAL = V_TOTAL + ST_EKKO-AMOUNT.

    AT END OF CURRENCY.
      TEMP_CURR = ST_EKKO-CURRENCY.
      WRITE: /'COMP. CODE: ', ST_EKKO-COMPANY_CODE,' NET AMOUNT:',TEMP_CURR, V_TOTAL.
      CLEAR V_TOTAL.
    ENDAT.
  ENDLOOP.